// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
//slider_start
var currentIndex = 0,
	items = $('.slider div'),
	itemAmt = items.length;

function cycleItems() {
	var item = $('.slider div').eq(currentIndex);
	items.hide();
	item.css('display','inline-block');
}

var autoSlide = setInterval(function() {
	currentIndex += 1;
	if (currentIndex > itemAmt - 1) {
		currentIndex = 0;
	}
	cycleItems();
}, 3000);

$('.next').click(function() {
	clearInterval(autoSlide);
	currentIndex += 1;
	if (currentIndex > itemAmt - 1) {
		currentIndex = 0;
	}
	cycleItems();
});

$('.prev').click(function() {
	clearInterval(autoSlide);
	currentIndex -= 1;
	if (currentIndex < 0) {
		currentIndex = itemAmt - 1;
	}
	cycleItems();
});

//slider_end

//popupForm_start

$(".registration").click(function() {
	$(".popup").css("display", "block");
	$(".regform").css("display", "block");
	$(".logform").css("display", "none");
});

$(".login").click(function() {
	$(".popup").css("display", "block");
	$(".regform").css("display", "none");
	$(".logform").css("display", "block");
});

$(".out").click(function() {
	$(".popup").css("display", "none");
	$(".regform").css("display", "none");
	$(".logform").css("display", "none");
	$(".askuser").css("display", "none");
});

$(".switch").click(function() {
	$(".regform").css("display", "none");
	$(".logform").css("display", "block");
});

$(".switch1").click(function() {
	$(".regform").css("display", "block");
	$(".logform").css("display", "none");
});

//popupForm_end